import React from 'react';
import { View, ScrollView, Text, TouchableOpacity, StyleSheet } from 'react-native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import { useSelector } from 'react-redux';
import SectionTitle from '../components/SectionTitle';
import Title from '../components/Title';
import Subtitle from '../components/Subtitle';

const DOA = ({ navigation }) => {
  const userInfo = useSelector((state) => state.bank.userInfo);
  const currentDate = new Date();
  const day = currentDate.getDate();
  const month = currentDate.toLocaleString('default', { month: 'long' });
  const year = currentDate.getFullYear();

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Ionicons name="arrow-back-outline" size={30} color="#4C28BC" />
        </TouchableOpacity>
        <View style={styles.headerContainer}>
          <Text style={styles.headerText}>DEED OF AGREEMENT</Text>
        </View>
      </View>

      <Title>Deed of Agreement</Title>
      <Subtitle>
        Agreement between {userInfo.firstName} {userInfo.lastName} and MyFund
      </Subtitle>

      <ScrollView style={styles.contentContainer}>
        <SectionTitle>INTRODUCTION</SectionTitle>
        <Text style={styles.bodyText}>
          This Deed of Agreement ("Agreement") is entered into on this {day} day of {month}, {year} (the "Effective Date") by and
          between:
        </Text>

        <SectionTitle>PARTIES</SectionTitle>
        <Text style={styles.bodyText}>
          WHEREAS, Party A ({userInfo.firstName} {userInfo.lastName}) is a registered user of the MyFund platform and intends to purchase
          properties through the platform.
        </Text>
        <Text style={styles.bodyText}>
          WHEREAS, Party B (MyFund) operates the MyFund platform and provides property investment opportunities to registered users, and operating at 13, Gbajabiamila Street, Ayobo, Lagos. And also via the webapp at www.myfundmobile.com. And can be contacted via the office line: +2349032719396.
        </Text>

        <SectionTitle>PROPERTY COST AND RENTAL INCOME</SectionTitle>
        <Text style={styles.bodyText}>
          1.1 Party A will pay the amount stated as cost on the property and agrees to a 5% charge for processing fee.
        </Text>
        <Text style={styles.bodyText}>
          1.2 Party A acknowledges that they will earn 70% of the rental income generated by the property purchased through the MyFund
          platform, and Party B shall deduct 30% as for managment fees. The rental income will be earned annually as long as the property is
          operational and earning rent.
        </Text>
        <Text style={styles.bodyText}>
          1.3 Party A understands that the rental income may increase over time, as it is calculated as a percentage of the property's
          rental earnings.
        </Text>

        <SectionTitle>WAITING PERIOD</SectionTitle>
        <Text style={styles.bodyText}>
          2.1 If the selected property has a waiting period attached to it, and party A wants to pay ahead as an early mover, Party A agrees to a waiting period of 9 months for the property purchased. Party B shall not list properties that are not
          expected to be available within this period.
        </Text>

        <SectionTitle>SALE OF PROPERTY</SectionTitle>
        <Text style={styles.bodyText}>
          3.1 If Party A wishes to sell a property, the property will be listed for sale on the MyFund platform, and the proceeds from the
          sale will be credited to Party A's wallet upon completion. A processing fee, typically between 5-10% of the sale price, will be
          deducted from the sale proceeds.
        </Text>
        <Text style={styles.bodyText}>
          3.2 Party A acknowledges that the sale price of the property may not be the same as the purchase price, as property values can
          fluctuate based on factors such as inflation and current property valuations. Property values may decrease, and Party A should be
          aware that properties may not appreciate in value like land.
        </Text>

        <SectionTitle>TRANSACTION COSTS</SectionTitle>
        <Text style={styles.bodyText}>
          4.1 Party A is responsible for all transaction costs associated with the purchase and sale of the property, including but not
          limited to legal fees, property transfer taxes, and any other expenses. Party A also acknowledges that they will forfeit the yearly
          rental income of the property upon the completion of the property's sale.
        </Text>

        <SectionTitle>APP-BASED TRANSACTIONS</SectionTitle>
        <Text style={styles.bodyText}>
          5.1 All transactions, communications, and activities related to the purchase, sale, and management of properties, including the
          calculation and distribution of rental income, shall be conducted through the MyFund mobile application. The Parties agree that using
          the app is essential for record-keeping and transparency.
        </Text>

        <SectionTitle>GOVERNING LAW</SectionTitle>
        <Text style={styles.bodyText}>
          6.1 This Agreement shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria.
        </Text>

        <SectionTitle>ENTIRE AGREEMENT</SectionTitle>
        <Text style={styles.bodyText}>
          7.1 This Agreement constitutes the entire agreement between the Parties and supersedes all prior and contemporaneous understandings,
          agreements, representations, and warranties.
        </Text>

        <TouchableOpacity style={styles.primaryButton} onPress={() => navigation.goBack()}>
        <Ionicons name="arrow-back-outline" size={30} color="#fff" />
          <Text style={styles.primaryButtonText}>  Confirmed, Go Back</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F1FF',
  },
  header: {
    marginTop: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: 'white',
    height: 43,
  },
  headerContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  
  headerText: {
    flex: 1,
    color: 'silver',
    alignSelf: 'center',
    marginLeft: 15,
    fontFamily: 'nexa',
    letterSpacing: 3,
  },
  contentContainer: {
    paddingHorizontal: 30,
    paddingTop: 20,
    paddingBottom: 60,
  },
  bodyText: {
    fontFamily: 'karla',
    fontSize: 15,
    marginBottom: 20,
    paddingHorizontal: 20,

  },
  primaryButton: {
    flexDirection: 'row',
    backgroundColor: '#4C28BC',
    width: '85%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 50,

  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'ProductSans',
    marginRight: 5,
  },
});

export default DOA;
