# Generated by Django 4.2.4 on 2023-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
