# Generated by Django 4.2.3 on 2023-08-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='Default Account Name', max_length=100),
        ),
    ]
