# Generated by Django 4.2.3 on 2023-08-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_otp_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_verified',
            new_name='is_confirmed',
        ),
    ]
