# Generated by Django 4.2.3 on 2023-08-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_preferred_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_time_signup',
            field=models.BooleanField(default=True),
        ),
    ]
