# Generated by Django 4.2.3 on 2023-08-28 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_accounts',
            field=models.ManyToManyField(blank=True, related_name='owners', to='authentication.bankaccount'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='owners', to='authentication.card'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
