# Generated by Django 4.2.3 on 2023-09-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='No description available', max_length=255),
        ),
    ]
