# Generated by Django 4.2.5 on 2023-09-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_autosave'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosave',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
