# Generated by Django 4.2.5 on 2023-09-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_autosave_transaction_id_autosave_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosave',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
