# Generated by Django 4.2.5 on 2023-09-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_autosave_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autosave_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
