# Generated by Django 4.2.5 on 2023-10-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_bankaccount_paystack_recipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
