# Generated by Django 4.2.5 on 2023-10-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_customuser_pending_referral_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='referral_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
