# Generated by Django 4.2.5 on 2023-10-27 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_alter_transaction_transaction_type_monthlysavings'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysavings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlysavings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
