# Generated by Django 4.2.5 on 2023-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_customuser_savings_and_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='top_saver_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
