# Generated by Django 4.2.5 on 2023-10-30 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_customuser_admin_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='Enter Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin_approval_status',
            field=models.CharField(default='Not yet started', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(choices=[('Unemployed', 'Unemployed'), ('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Business', 'Business'), ('Retired', 'Retired')], default='Choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], default='Choose', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification_type',
            field=models.CharField(choices=[('International Passport', 'International Passport'), ("Driver's License", "Driver's License"), ('National ID Card (NIN)', 'National ID Card (NIN)'), ("Permanent Voter's Card", "Permanent Voter's Card")], default='Choose', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(default='Not yet started', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mothers_maiden_name',
            field=models.CharField(default='Enter Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_of_kin_name',
            field=models.CharField(default='Enter Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_of_kin_phone_number',
            field=models.CharField(default='Enter Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='relationship_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Remarried', 'Remarried')], default='Choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='relationship_with_next_of_kin',
            field=models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Father', 'Father'), ('Mother', 'Mother'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Friend', 'Friend'), ('Relative', 'Relative')], default='Choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='yearly_income',
            field=models.CharField(choices=[('Less than N200,000', 'Less than N200,000'), ('N200001 - N500000', 'N200001 - N500000'), ('N500000 - N1million', 'N500000 - N1million'), ('N1million - N5million', 'N1million - N5million'), ('N5million - N10million', 'N5million - N10million'), ('N10million - N20 million', 'N10million - N20 million'), ('Above N20million', 'Above N20million')], default='Choose', max_length=30),
        ),
    ]
