# Generated by Django 4.2.5 on 2023-10-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0047_alter_customuser_kyc_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="kyc_status",
            field=models.CharField(default="Not yet started", max_length=20),
        ),
    ]
