# Generated by Django 4.2.5 on 2023-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0048_alter_customuser_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_savings_and_investments_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(choices=[('Unemployed', 'Unemployed'), ('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Business', 'Business'), ('Retired', 'Retired'), ('Student', 'Student'), ('Others', 'Others')], default='Choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification_type',
            field=models.CharField(choices=[('International Passport', 'International Passport'), ("Driver's License", "Driver's License"), ('National ID Card (NIN)', 'National ID Card (NIN)'), ("Permanent Voter's Card", "Permanent Voter's Card"), ('Bank Verification Number (BVN)', 'Bank Verification Number (BVN)'), ('Others', 'Others')], default='Choose', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='relationship_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Remarried', 'Remarried'), ('Widowed', 'Widowed'), ('Others', 'Others')], default='Choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='relationship_with_next_of_kin',
            field=models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Father', 'Father'), ('Mother', 'Mother'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Friend', 'Friend'), ('Relative', 'Relative'), ('Others', 'Others')], default='Choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='yearly_income',
            field=models.CharField(choices=[('Less than N200000', 'Less than N200000'), ('N200001 - N500000', 'N200001 - N500000'), ('N500001 - N1 million', 'N500001 - N1 million'), ('N1 million - N5 million', 'N1 million - N5 million'), ('N5 million - N10 million', 'N5 million - N10 million'), ('N10 million - N20 million', 'N10 million - N20 million'), ('Above N20 million', 'Above N20 million')], default='Choose', max_length=30),
        ),
    ]
