# Generated by Django 4.2.5 on 2023-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_customuser_total_savings_and_investments_this_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysavings',
            old_name='total_savings_and_investments',
            new_name='investment',
        ),
        migrations.RemoveField(
            model_name='monthlysavings',
            name='created_at',
        ),
        migrations.AddField(
            model_name='monthlysavings',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
