# Generated by Django 4.2.5 on 2023-11-02 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_rename_total_savings_and_investments_monthlysavings_investment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysavings',
            old_name='investment',
            new_name='total_savings_and_investments',
        ),
        migrations.RemoveField(
            model_name='monthlysavings',
            name='savings',
        ),
        migrations.AddField(
            model_name='monthlysavings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
