# Generated by Django 4.2.5 on 2023-11-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0051_rename_investment_monthlysavings_total_savings_and_investments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysavings',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='monthlysavings',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
