# Generated by Django 4.2.5 on 2023-11-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0053_alter_monthlysavings_total_savings_and_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_savings_and_investments_this_month',
        ),
    ]
