# Generated by Django 4.2.5 on 2023-11-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0054_remove_customuser_total_savings_and_investments_this_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_savings_and_investments_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
