# Generated by Django 4.2.5 on 2023-11-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_remove_monthlysavings_total_savings_and_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysavings',
            name='total_savings_and_investments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
