# Generated by Django 4.2.5 on 2023-11-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0057_monthlysavings_total_savings_and_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysavings',
            name='total_savings_and_investments',
        ),
    ]
