# Generated by Django 4.2.5 on 2023-11-04 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings_and_investments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_wallet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_active_users', models.IntegerField()),
                ('total_dormant_users', models.IntegerField()),
                ('pending_kyc_approvals', models.IntegerField()),
                ('total_savings_and_investments_this_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
