# Generated by Django 4.2.5 on 2024-02-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0065_alter_customuser_admin_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
