# Generated by Django 5.0 on 2024-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0069_customuser_how_did_you_hear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='myfund_pin',
            field=models.CharField(blank=True, null=True),
        ),
    ]
